import {
  HabitCategory,
  HabitFrequency,
  HabitDifficulty,
  AttributeType,
} from '../habits/entities/habit.entity';

export interface SystemHabitSeed {
  name: string;
  description: string;
  category: HabitCategory;
  frequency: HabitFrequency;
  xpReward: number;
  attributeType: AttributeType;
  attributeReward: number;
  difficulty: HabitDifficulty;
  iconName: string;
  isSystemHabit: true;
  isActive: true;
}

export const SYSTEM_HABITS: SystemHabitSeed[] = [
  // FITNESS
  {
    name: 'Treino Fisico',
    description: 'Complete um treino fisico intenso para fortalecer seu corpo',
    category: HabitCategory.FITNESS,
    frequency: HabitFrequency.DAILY,
    xpReward: 50,
    attributeType: AttributeType.STRENGTH,
    attributeReward: 5,
    difficulty: HabitDifficulty.MEDIUM,
    iconName: 'dumbbell',
    isSystemHabit: true,
    isActive: true,
  },
  {
    name: 'Caminhada 30min',
    description: 'Faca uma caminhada de pelo menos 30 minutos',
    category: HabitCategory.FITNESS,
    frequency: HabitFrequency.DAILY,
    xpReward: 30,
    attributeType: AttributeType.STRENGTH,
    attributeReward: 3,
    difficulty: HabitDifficulty.EASY,
    iconName: 'walk',
    isSystemHabit: true,
    isActive: true,
  },
  {
    name: 'Alongamento',
    description: 'Realize uma sessao de alongamento para melhorar flexibilidade',
    category: HabitCategory.FITNESS,
    frequency: HabitFrequency.DAILY,
    xpReward: 20,
    attributeType: AttributeType.STRENGTH,
    attributeReward: 2,
    difficulty: HabitDifficulty.EASY,
    iconName: 'stretch',
    isSystemHabit: true,
    isActive: true,
  },

  // STUDY
  {
    name: 'Estudar 1 hora',
    description: 'Dedique 1 hora focada aos seus estudos',
    category: HabitCategory.STUDY,
    frequency: HabitFrequency.DAILY,
    xpReward: 60,
    attributeType: AttributeType.INTELLIGENCE,
    attributeReward: 6,
    difficulty: HabitDifficulty.MEDIUM,
    iconName: 'book-open',
    isSystemHabit: true,
    isActive: true,
  },
  {
    name: 'Ler 30 paginas',
    description: 'Leia pelo menos 30 paginas de um livro',
    category: HabitCategory.STUDY,
    frequency: HabitFrequency.DAILY,
    xpReward: 40,
    attributeType: AttributeType.INTELLIGENCE,
    attributeReward: 4,
    difficulty: HabitDifficulty.MEDIUM,
    iconName: 'book',
    isSystemHabit: true,
    isActive: true,
  },
  {
    name: 'Praticar idioma',
    description: 'Pratique um idioma estrangeiro por pelo menos 20 minutos',
    category: HabitCategory.STUDY,
    frequency: HabitFrequency.DAILY,
    xpReward: 30,
    attributeType: AttributeType.INTELLIGENCE,
    attributeReward: 3,
    difficulty: HabitDifficulty.EASY,
    iconName: 'language',
    isSystemHabit: true,
    isActive: true,
  },

  // MENTAL
  {
    name: 'Meditar 15min',
    description: 'Medite por 15 minutos para fortalecer sua mente',
    category: HabitCategory.MENTAL,
    frequency: HabitFrequency.DAILY,
    xpReward: 40,
    attributeType: AttributeType.DISCIPLINE,
    attributeReward: 4,
    difficulty: HabitDifficulty.MEDIUM,
    iconName: 'brain',
    isSystemHabit: true,
    isActive: true,
  },
  {
    name: 'Journaling',
    description: 'Escreva em seu diario sobre seus pensamentos e progresso',
    category: HabitCategory.MENTAL,
    frequency: HabitFrequency.DAILY,
    xpReward: 30,
    attributeType: AttributeType.INTELLIGENCE,
    attributeReward: 3,
    difficulty: HabitDifficulty.EASY,
    iconName: 'pencil',
    isSystemHabit: true,
    isActive: true,
  },
  {
    name: 'Sem redes sociais 2h',
    description: 'Fique pelo menos 2 horas sem acessar redes sociais',
    category: HabitCategory.MENTAL,
    frequency: HabitFrequency.DAILY,
    xpReward: 50,
    attributeType: AttributeType.DISCIPLINE,
    attributeReward: 5,
    difficulty: HabitDifficulty.HARD,
    iconName: 'shield',
    isSystemHabit: true,
    isActive: true,
  },

  // DISCIPLINE
  {
    name: 'Acordar cedo',
    description: 'Acorde antes das 7h da manha',
    category: HabitCategory.DISCIPLINE,
    frequency: HabitFrequency.DAILY,
    xpReward: 40,
    attributeType: AttributeType.DISCIPLINE,
    attributeReward: 4,
    difficulty: HabitDifficulty.MEDIUM,
    iconName: 'sunrise',
    isSystemHabit: true,
    isActive: true,
  },
  {
    name: 'Organizar ambiente',
    description: 'Organize e limpe seu espaco de trabalho ou quarto',
    category: HabitCategory.DISCIPLINE,
    frequency: HabitFrequency.DAILY,
    xpReward: 25,
    attributeType: AttributeType.DISCIPLINE,
    attributeReward: 2,
    difficulty: HabitDifficulty.EASY,
    iconName: 'sparkles',
    isSystemHabit: true,
    isActive: true,
  },
  {
    name: 'Sem junk food',
    description: 'Passe o dia sem consumir junk food ou ultraprocessados',
    category: HabitCategory.DISCIPLINE,
    frequency: HabitFrequency.DAILY,
    xpReward: 35,
    attributeType: AttributeType.DISCIPLINE,
    attributeReward: 3,
    difficulty: HabitDifficulty.MEDIUM,
    iconName: 'apple',
    isSystemHabit: true,
    isActive: true,
  },

  // HEALTH
  {
    name: 'Beber 2L agua',
    description: 'Beba pelo menos 2 litros de agua durante o dia',
    category: HabitCategory.HEALTH,
    frequency: HabitFrequency.DAILY,
    xpReward: 20,
    attributeType: AttributeType.DISCIPLINE,
    attributeReward: 2,
    difficulty: HabitDifficulty.EASY,
    iconName: 'droplet',
    isSystemHabit: true,
    isActive: true,
  },
  {
    name: 'Dormir 8h',
    description: 'Durma pelo menos 8 horas de sono de qualidade',
    category: HabitCategory.HEALTH,
    frequency: HabitFrequency.DAILY,
    xpReward: 40,
    attributeType: AttributeType.DISCIPLINE,
    attributeReward: 4,
    difficulty: HabitDifficulty.MEDIUM,
    iconName: 'moon',
    isSystemHabit: true,
    isActive: true,
  },
  {
    name: 'Tomar vitaminas',
    description: 'Tome seus suplementos e vitaminas diarios',
    category: HabitCategory.HEALTH,
    frequency: HabitFrequency.DAILY,
    xpReward: 15,
    attributeType: AttributeType.DISCIPLINE,
    attributeReward: 1,
    difficulty: HabitDifficulty.EASY,
    iconName: 'pill',
    isSystemHabit: true,
    isActive: true,
  },
];
